name: Build and Upload Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        find . -path '*/target/HuskSync*' -exec cp --parents {} artifacts \;

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HuskSync-Build-Output
        path: artifacts/